### ISSUE TITLE
Improve intro txt on the home page

### ISSUE THREAD

**Issue by clemsos** [costoffreedom/costoffreedom.cc#28]
@geertlovink said  

> "The Cost of Freedom is a book that was written in Pourrières, France from November 2nd to 6th, 2015. This book is not a statement about freedom and culture — it is a primal scream — the sum of our questions and desires. It is the raw expression of our lives. It talks about what is ultimately made through the dream of free culture: us.”

I would advice to rewrite this central piece of information about the project. It is unclear, mystifies and is an invitation to read the book. Maybe a native-English copy editor can help out.

[link to the original discussion]()

**Comment by mlinksva** [comment]
Well, it's an invitation to read the book. That's good. I don't see an easy improvement, so closing.

**Comment by hellekin** [comment]
There's room for improvement.  Reopening.

**Comment by hellekin** [comment]
- When did we last receive new of Bassel and what was it?
- What's changed in Syria since we wrote this book?
- What's changed in EU since we wrote this book?

Starting points for "re-opening" the book opening.

Instead of "It is the raw expression of our lives", it could mention the _condensation of decades of action_ into a brain dump or something.  Maybe a brain dump is a tad too raw.  But I guess clemsos wanted something that resembles less the voice of a circus presenter calling for the show.  It was written in the fire of production, with half the people gone, and reflected a common euphoria at this point.  Now that time has passed, something more sober would be welcome.

**Comment by clemsos** [comment]
I will keep the text of the book as is. I think it actually works well. Anyway we need a text for the back cover of the print version, so maybe a way to write something introductory here

**Comment by clemsos** [comment]
current cover 

![selection_115](https://cloud.githubusercontent.com/assets/743246/14911311/f6260936-0df4-11e6-8357-2492a2909ade.png)

**Comment by ghost** [comment]
Good work, done.
